# Supported values: debug, info, warn, error.
log_level: info

client_whitelist:
  # - 192.0.2.10
  # - 198.51.100.0/24
  # - 2001:db8::/64

domain_whitelist:
  # - example.com
  # - ipv6.example.com

routes:
  # example.com:
  #   host: 203.0.113.10
  #   ip_family: ipv4
  #   outbound_ip: 198.51.100.20
  # pool.example.com:
  #   outbound_ip: 198.51.100.20/24
  # ipv6.example.com:
  #   host: 2001:db8::10
  #   ip_family: ipv6
  #   outbound_ip: 2001:db8::20/64
