# Supported values: debug, info, warn, error.
log_level: info

client_whitelist:
  # - 192.0.2.10
  # - 198.51.100.0/24
  # - 2001:db8::/64

hosts:
  # example.com: 203.0.113.10

ip_family:
  # example.com: ipv4
  # ipv6.example.com: ipv6

outbound_ip:
  # example.com: 198.51.100.20
  # pool.example.com: 198.51.100.20/24
  # ipv6.example.com: 2001:db8::20
  # ipv6-pool.example.com: 2001:db8::20/64
